[workspace]
resolver = "3"
members = [
  "oscrc",
  "obsctl",
  "open-build-service-api",
  "open-build-service-mock"
]

[workspace.package]
repository = "https://github.com/collabora/open-build-service-rs"
homepage = "https://github.com/collabora/open-build-service-rs"
